# Generated by Django 4.0.5 on 2022-06-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=0, upload_to='user_images/'),
            preserve_default=False,
        ),
    ]
