# Generated by Django 4.0.5 on 2022-06-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_group_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
