# Generated by Django 4.0.5 on 2022-06-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usergroupbridge_transaction_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroupbridge',
            old_name='User',
            new_name='user',
        ),
    ]
