# Generated by Django 4.0.5 on 2022-06-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
