# Generated by Django 4.0.5 on 2022-06-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_transaction_description_transaction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(default='#', null=True, upload_to='Transaction_images/'),
        ),
    ]
