# Generated by Django 4.0.5 on 2022-07-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to='group_images/'),
        ),
    ]
