# Generated by Django 4.0.5 on 2022-07-09 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usergroupbridge_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
    ]
