# Generated by Django 4.0.5 on 2022-07-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_transaction_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(default='group_images/no-image.jpg', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='image',
            field=models.ImageField(default='group_images/no-image.jpg', upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
